services:
  mobileapi:
    build:
      dockerfile: ./Dockerfile
    container_name: mobileapi
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "80:8080"
    networks:
      - mobileapi

networks:
  mobileapi:
